-- Import des développeurs chypriotes dans la table developers
-- Date: 2025-01-27
-- Données: 21 développeurs de Paphos et Limassol

-- 1. AGG Luxury Homes Ltd
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales, email_marketing,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'AGG Luxury Homes Ltd',
    1978,
    'Fondée en 1978, AGG Luxury Homes s''est établie comme spécialiste des résidences de luxe modernes à Paphos, mettant l''accent sur le service personnalisé et les constructions de haute qualité. Avec plus de 35 projets réalisés, elle s''adresse aux acheteurs de résidences secondaires en alliant design contemporain et esthétique chypriote.',
    'Développement de propriétés résidentielles de luxe, incluant villas et complexes, avec un accent sur les designs sur mesure et la qualité premium.',
    'Villas d''élite et complexes résidentiels dans les zones privilégiées de Paphos ; plus de 35 projets au total.',
    'Paphos',
    ARRAY['4, 25th March Street, Paphos 8047, Cyprus']::TEXT[],
    'https://www.agcyprus.com/',
    ARRAY['+357 26 813171', '+357 80 006363']::TEXT[],
    'info@agcyprus.com',
    'sales@agcyprus.com, marketing@agcyprus.com',
    'marketing@agcyprus.com',
    'Commentaires très positifs sur des plateformes comme Facebook et home.cy (moyenne de 4,8/5), avec des prix pour les développements de luxe ; quelques notes sur les prix premium.',
    'Établie de longue date sans problèmes signalés ; stable en tant qu''entreprise de taille moyenne sur un marché résilient.',
    8.0,
    'Excellente réputation et qualité de projet, mais l''échelle limitée par rapport aux groupes plus importants tempère légèrement le score ; idéal pour les acheteurs recherchant du luxe sur mesure.',
    35,
    47,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    email_marketing = EXCLUDED.email_marketing,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 2. Aristo Developers
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'Aristo Developers',
    1980,
    'Établie en 1980, Aristo est devenue pionnière avec plus de 265 projets à travers Chypre et la Grèce, spécialisée dans les complexes de golf, les institutions éducatives et les investissements à grande échelle. Connue pour l''innovation et les soutiens internationaux.',
    'Développement de propriétés résidentielles, commerciales et de villégiature, incluant des terrains de golf et des installations éducatives ; accent sur l''innovation et les investissements à grande échelle.',
    'Venus Rock Golf Resort ; plus de 265 projets, avec 223 propriétés en cours.',
    'Les deux',
    ARRAY['8 April 1st Street, Paralimni 5280, Cyprus', 'Aristo Centre, 8 Apriliou 1st Street, P.O. Box 60269, CY-8101 Paphos']::TEXT[],
    'https://www.aristodevelopers.com/',
    ARRAY['+357 26 841800']::TEXT[],
    'info@aristodevelopers.com',
    'sales@aristodevelopers.com',
    'Très bien considérée avec des prix comme "Best Property Development Team Cyprus 2020" ; retours mitigés sur les délais hors plan mais globalement positifs (ex : "fiable" dans les forums).',
    'Plus de 40 ans de croissance stable ; certifié ISO 9001 ; aucun signal d''alarme financier.',
    9.0,
    'Forte présence sur le marché, prix et échelle ; des préoccupations mineures hors plan empêchent un score parfait, mais un choix de premier plan pour les investisseurs.',
    265,
    45,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 3. Crona Property (Crona Group)
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'Crona Property (Crona Group)',
    2007,
    'Fondée en 2007, Crona Group est un consortium avec plus de 20 ans d''expérience, évoluant vers un développeur immobilier à service complet à Chypre, complétant plus de 50 projets et employant 300+ professionnels.',
    'Développement immobilier cycle complet de la conception à l''achèvement, incluant propriétés premium, assistance à l''achat, permis de résidence, location, investissements et maintenance ; détient la licence de construction de premier niveau.',
    'Garden Square (appartements/villas, Limassol) ; Onyx Residence (appartements, Limassol) ; Gateway Offices/Residences (en développement, Limassol) ; Amissos (appartements, Limassol) ; Ariadne (appartements/villas, Limassol) ; Green Hills (appartements, Limassol) ; plus de 50 complétés.',
    'Limassol',
    ARRAY['21 Andrea Kariolou Street, Agios Athanasios, Limassol 4102, Cyprus']::TEXT[],
    'https://www.cronagroup.com/',
    ARRAY['+357 25 280000', '+357 25 055961']::TEXT[],
    'info@cronagroup.com',
    'sales@cronagroup.com, info@cronaproperty.com',
    'Met l''accent sur la qualité, la confiance et l''excellence ; positif comme "fiable" dans les avis ; aucun prix spécifique mentionné, mais position solide auto-déclarée.',
    'Stable en tant que partie d''un groupe plus large ; aucun problème noté, mais moins de transparence que les entreprises plus anciennes.',
    7.0,
    'Opérations solides et volume de projets, mais critiques publiques clairsemées et échelle intermédiaire limitent un score plus élevé ; convient aux acheteurs premium de Limassol.',
    50,
    18,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 4. Cybarco (incl. Lanitis Development)
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'Cybarco (incl. Lanitis Development)',
    1945,
    'Cybarco fondée en 1945 dans le cadre du groupe Lanitis (établi fin 1800, dirigé par la famille de quatrième génération) ; un acteur majeur dans les développements de luxe et les infrastructures avec une portée internationale.',
    'Développement immobilier, construction, tourisme, hôtels, transport, loisirs, golf, marina, énergie, commerce, agriculture ; accent sur le service de qualité et la durabilité.',
    'Repères significatifs dans les deux villes ; accent sur l''après-vente et la durabilité ; projets spécifiques non détaillés dans les sources.',
    'Les deux',
    ARRAY['9 Georgiou Gennadiou, Limassol 3041', '21 Arch. Kyprianou Street, Limassol 3036', 'Konia Industrial Area, 8300 Paphos']::TEXT[],
    'https://www.cybarco.com/',
    ARRAY['+357 22 741300', '+357 25 820920', '+357 26 913313']::TEXT[],
    'info@cybarco.com',
    'sales@cybarco.com',
    'Excellents éloges pour la cohérence et l''intégrité ; opérations résilientes après les défis.',
    'Soutenu par un grand groupe avec des finances solides ; longue histoire garantit la stabilité.',
    9.0,
    'Héritage prestigieux et prix ; les notes opérationnelles mineures ne nuisent pas à l''excellence globale.',
    NULL,
    80,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 5. Cyfield Group
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales, email_marketing,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'Cyfield Group',
    1990,
    'Fondée en 1990, Cyfield est devenue un leader dans l''immobilier, l''énergie et les infrastructures, complétant plus de 400 projets avec un accent sur la technologie et l''efficacité.',
    'Développement immobilier, énergie, infrastructure ; gratte-ciel modernes et initiatives renouvelables.',
    'Gratte-ciel modernes et projets d''énergie renouvelable ; plus de 400 au total.',
    'Limassol',
    ARRAY['CYFIELD TOWER, 132 Limassol Avenue, Nicosia 2015, Cyprus']::TEXT[],
    'https://www.cyfieldgroup.com/',
    ARRAY['+357 22 427230']::TEXT[],
    'info@cyfieldgroup.com',
    'sales@cyfieldgroup.com',
    'marketing@cyfieldgroup.com',
    'Designs innovants loués, mais quelques critiques sur les liens gouvernementaux et l''éthique dans les forums.',
    'Forte avec diversification ; pas d''échecs majeurs.',
    7.0,
    'Prouesse technique compensée par la controverse ; équilibré pour les acheteurs éthiques.',
    400,
    35,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    email_marketing = EXCLUDED.email_marketing,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 6. D. Zavos Group
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'D. Zavos Group',
    1980,
    'Établi en 1980, se concentre sur les projets résidentiels de luxe avec plus de 165 développements, s''étendant en Grèce.',
    'Développement de propriétés résidentielles haut de gamme ; focus international de luxe.',
    'Achèvements abordables 2024 ; plus de 130-165 projets.',
    'Les deux',
    ARRAY['1 Griva Digenis Street, Limassol 3302', '1 Grivas Dhigenis Avenue, Zavos Kriel Court, P.O. Box 53311, 3035 Limassol']::TEXT[],
    'https://zavos.com/',
    ARRAY['+357 25 818555']::TEXT[],
    'info@zavos.com',
    'sales@zavos.com',
    'Service et valeur solides ; positif sur les réseaux sociaux.',
    'Bilan solide ; orienté croissance.',
    8.0,
    'Fiable avec expansion, mais le marché concurrentiel limite la perfection.',
    165,
    45,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 7. Domenica Group
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales, email_marketing,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'Domenica Group',
    1961,
    'Fondée en 1961, une pierre angulaire à Paphos avec 32+ projets autofinancés, mettant l''accent sur la qualité et le risque réduit.',
    'Développement résidentiel dans les zones privilégiées ; modèle d''autofinancement.',
    'Complexes résidentiels ; environ 32 projets.',
    'Paphos',
    ARRAY['12 Demokratias Avenue, Pafos 8045/8066, Cyprus']::TEXT[],
    'https://domenicagroup.com/',
    ARRAY['+357 26 600700', '+357 80 008010']::TEXT[],
    'info@domenicagroup.com',
    'sales@domenicagroup.com',
    'marketing@domenicagroup.com',
    'Très positif, "fiable" dans les forums ; prix pour l''excellence.',
    'L''autofinancement garantit la robustesse.',
    9.0,
    'Longévité et modèle à faible risque brillent ; top pour les chercheurs de stabilité.',
    32,
    64,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    email_marketing = EXCLUDED.email_marketing,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 8. Imperio Properties
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'Imperio Properties',
    2003,
    'Fondée le 10 octobre 2003, Imperio Properties s''est concentrée sur des projets résidentiels et commerciaux durables et innovants depuis sa création, avec l''objectif de créer des propriétés méritantes.',
    'Développement de propriétés résidentielles et commerciales durables ; initiatives communautaires comme le parrainage d''événements.',
    'Silicon Park ; Imperio Portside ; Imperio Skyline ; Sunset Gardens ; Imperio House ; The Icon ; environ 50 projets.',
    'Limassol',
    ARRAY['8 Ayiou Prokopiou Street, Engomi, Nicosia 2406', 'Imperio House, 5 Kedron, Mesa Geitonia, 4004 Limassol']::TEXT[],
    'https://www.imperioproperties.com/',
    ARRAY['+357 22 458777', '+357 25 581005']::TEXT[],
    'info@imperio-properties.com',
    'sales@imperio-properties.com',
    'Loué pour la modernité et la durabilité ; prix comme Best Residential Apartment Cyprus 2009.',
    'Stable avec un focus éco aidant la résilience ; pas de problèmes majeurs.',
    8.0,
    'Innovation forte, mais histoire plus courte que les pairs.',
    50,
    22,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 9. INEX Group
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    years_experience, commission_rate, status
) VALUES (
    'INEX Group',
    2010,
    'Fondé vers 2010, INEX Group est un pionnier de l''immobilier écologique avec 15 ans d''expérience, se concentrant sur le développement intelligent pour les projets résidentiels et commerciaux.',
    'Développement à grande échelle incluant construction, architecture, design, ingénierie, planification ; accent sur les projets centrés sur l''humain et écologiques.',
    'Développements résidentiels/commerciaux uniques ; projets spécifiques non détaillés, mais accent sur l''amélioration des standards de vie.',
    'Paphos',
    ARRAY['58 Leoforos Ellados, Paphos 8020', '10 Apostolou Pavlou Avenue, Paphos 8046']::TEXT[],
    'https://inex-development.com/',
    ARRAY['+357 777 888 33']::TEXT[],
    'info@inex-development.com',
    'sales@inex-development.com, info@inex-group.com',
    'Positif mais clairsemé ; perspectives du PDG sur les défis du marché notées.',
    'Semble stable ; pas de signaux d''alarme, non financé mais compétitif.',
    7.0,
    'Bonne intention et focus éco, mais données limitées et présence plus récente empêchent un score plus élevé.',
    15,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 10. Island Blue
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'Island Blue',
    1985,
    'Établie vers 1985, Island Blue est un développeur primé à Paphos avec plus de 40 ans de croissance continue, se concentrant sur les développements luxueux haut de gamme.',
    'Développement d''appartements et de villas de luxe à Paphos et Limassol ; s''adresse aux acheteurs et investisseurs.',
    'IBC Tower (commercial, Paphos) ; Avalon Gardens 2 (studios, appartements, villas, Emba) ; Sapphire (Kato Paphos) ; 26+ projets.',
    'Paphos',
    ARRAY['Gladstonos 24, Poullet Court, Office No. 3, Pafos 8046, Cyprus']::TEXT[],
    'https://www.islandbluecyprus.com/',
    ARRAY['+357 26 222565', '+357 80 003377']::TEXT[],
    'info@islandbluecyprus.com',
    'sales@islandbluecyprus.com',
    'Notes élevées (4,8/5) ; 5 International Property Awards ; réputation d''entreprise exceptionnelle.',
    'Stable de niveau intermédiaire avec succès constant.',
    8.0,
    'Fort dans le luxe de niche ; l''échelle limite mais les prix augmentent.',
    26,
    40,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 11. Karma Group (Karma Developers)
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'Karma Group (Karma Developers)',
    1985,
    'Fondé en 1985, Karma Group a développé 4 000+ propriétés dans l''est de Chypre, s''étendant avec une approche centrée sur les personnes.',
    'Développement résidentiel ; focus sur l''est de Chypre mais noté dans les contextes de Paphos.',
    'Setai Residences ; 4 000+ propriétés.',
    'Paphos',
    ARRAY['16 Kennedy Avenue, Kapparis, Paralimni 5290, Cyprus']::TEXT[],
    'https://karma.cy/',
    ARRAY['+357 23 730777', '+357 80 030303']::TEXT[],
    'info@karmadevelopers.com.cy',
    'sales@karmadevelopers.com.cy',
    'Retours positifs solides ; valeur intemporelle soulignée.',
    'Fondations solides avec long historique.',
    8.0,
    'Héritage bon, mais focus régional limite l''attrait plus large.',
    4000,
    40,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 12. Korantina Homes
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    years_experience, commission_rate, status
) VALUES (
    'Korantina Homes',
    1990,
    'Établie en 1990, Korantina Homes est devenue un développeur prestigieux d''immobilier résidentiel de luxe et de resorts, complétant des projets de haute qualité et en expansion en construction.',
    'Conception et création de résidences et resorts de luxe sur mesure ; sélection d''emplacements pour bord de mer, ville ou intimité.',
    'Cap St Georges Hotel & Resort ; Soho Resort ; résidences opulentes.',
    'Paphos',
    ARRAY['32 Trikomou Street, Pegeia, Pafos 8560, Cyprus']::TEXT[],
    'https://korantinahomes.com/',
    ARRAY['+357 80 007030', '+357 26 623536']::TEXT[],
    'info@korantinahomes.com',
    'sales@korantinahomes.com',
    'Réputation internationale primée ; engagement envers des projets uniques. Une controverse liée aux investisseurs.',
    'Forte avec reconnaissance internationale.',
    8.0,
    'Excellence tempérée par des problèmes isolés.',
    35,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 13. Kuutio Homes
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'Kuutio Homes',
    2015,
    'Enregistrée en 2015, Kuutio Homes se concentre sur les propriétés de luxe sur mesure à Paphos, avec 34+ projets utilisant des matériaux naturels et l''efficacité énergétique.',
    'Livraison de maisons de luxe uniques et durables ; gestion professionnelle.',
    'Villas et appartements uniques ; 34+ projets, primés.',
    'Paphos',
    ARRAY['34 Nikolaou I. Nikolaidi Ave, 8010 Paphos, Cyprus']::TEXT[],
    'https://kuutiohomes.com/',
    ARRAY['+357 70 071313']::TEXT[],
    'info@kuutiohomes.com',
    'sales@kuutiohomes.com',
    'Accent positif sur l''art ; primé internationalement.',
    'Innovateur stable.',
    8.0,
    'Excellence de niche ; bon pour les besoins personnalisés.',
    34,
    10,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 14. Lemon Maria Developers
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    years_experience, commission_rate, status
) VALUES (
    'Lemon Maria Developers',
    1993,
    'Fondée en 1993, spécialisée dans les propriétés premium à Paphos.',
    'Développement de propriétés résidentielles de luxe.',
    'Ester Villas.',
    'Paphos',
    ARRAY['21 Neophytou Nicolaide Avenue, Paphos 8011, Cyprus']::TEXT[],
    'https://lemonmaria.com/',
    ARRAY['+357 26 942143', '+357 80 006030']::TEXT[],
    'info@lemonmaria.com',
    'Crédible avec retours positifs.',
    'Établie de niveau intermédiaire.',
    7.0,
    'Solide mais portée limitée.',
    32,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 15. Leptos Estates
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'Leptos Estates',
    1960,
    'Plus de 60 ans, avec 325+ projets ; leader à Chypre et en Grèce.',
    'Développements résidentiels et éco-développements à grande échelle.',
    'Neapolis Smart EcoCity ; 325+ projets.',
    'Les deux',
    ARRAY['136 Lord Byron Avenue, Neapolis, Limassol', '111 Apostolos Pavlos Avenue, CY-8046, P.O. Box 60146, CY-8129 Paphos', '104 Amathountos Avenue, Shop 5, 4532 Agios Tychona']::TEXT[],
    'https://www.leptosestates.com/',
    ARRAY['+357 26 880100', '+357 25 873233']::TEXT[],
    'info@leptosestates.com',
    'sales@leptosestates.com',
    'Mixte sur les délais mais prix solides.',
    'Excellente avec vaste banque foncière.',
    9.0,
    'L''échelle et l''histoire dominent ; avis mineurs notés.',
    325,
    65,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 16. Medousa Developers
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'Medousa Developers',
    2001,
    'Fondée en 2001 par Christakis Loizou, commençant comme une modeste entreprise de construction, maintenant plus de 20 ans dans le développement durable avec 10+ projets.',
    'Construction commerciale et résidentielle ; accent sur la durabilité.',
    'Infinity Residences ; Elite Residences ; Panorama Apartments ; Cypress Park ; ~10 projets.',
    'Paphos',
    ARRAY['Chiou Street 7, Paphos 8027, Cyprus']::TEXT[],
    'https://medousadevelopers.com/',
    ARRAY['+357 26 910910', '+357 80 009944']::TEXT[],
    'info@medousadevelopers.com',
    'sales@medousadevelopers.com',
    'Prix pour les éco-développements ; position positive dans l''industrie.',
    'Entrepreneur de classe A fiable.',
    8.0,
    'Durabilité forte ; bon pour les investisseurs verts.',
    10,
    24,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 17. Olias Homes
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'Olias Homes',
    2002,
    'Fondée en 2002, spécialisée dans le luxe sur mesure à Paphos avec 55+ projets.',
    'Développement résidentiel de luxe.',
    'Allegra Homes ; ~55 projets.',
    'Paphos',
    ARRAY['56 Eleftheriou Venizelou Street, 8021 Paphos, Cyprus']::TEXT[],
    'https://oliashomes.com/',
    ARRAY['+357 26 222288']::TEXT[],
    'sales@oliashomes.com',
    'sales@oliashomes.com',
    'Positif, orienté détail.',
    'Stable avec historique.',
    8.0,
    'L''exclusivité attire ; solide niveau intermédiaire.',
    55,
    23,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 18. Pafilia
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'Pafilia',
    1977,
    'Plus de 45 ans avec un portefeuille de 3 milliards d''euros et 250+ développements.',
    'Développement immobilier à grande échelle ; entreprise familiale.',
    'ONE Tower ; 250+ développements.',
    'Les deux',
    ARRAY['Pafilia House, 33 Nicodemou Mylona Street, Marina Court, P.O. Box 60159, 8101 Pafos', '307-309, 28th October Avenue, 3105 Limassol']::TEXT[],
    'https://www.pafilia.com/',
    ARRAY['+357 26 848800', '+357 25 590880']::TEXT[],
    'info@pafilia.com',
    'sales@pafilia.com, enquiries@pafilia.com',
    'Visionnaire avec multiples prix.',
    'Structure familiale solide.',
    9.0,
    'Excellence dans l''échelle et l''innovation.',
    250,
    48,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 19. P.L. Property Gallery Developers & Constructors
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'P.L. Property Gallery Developers & Constructors',
    2003,
    'Plus de 20 ans sur le marché, avec 55+ projets valant 800M€ et 500 000 m² ; multi-primé, incluant des développements hôteliers.',
    'Développement résidentiel, commercial, hôtelier ; villas, appartements, hôtels.',
    'YOO Limassol ; MIR Residences ; Homer Residences ; Majestic Villas ; Pissouri Forest Park ; Greenwood at Platres ; Petit Palais Hotel ; Platres Arena ; Dream Tower ; 55+ projets.',
    'Limassol',
    ARRAY['Ambelakion 28 Street, Germasogeia, Limassol 4046', '1 Georgiou A'' Street, Monastiraki Center, Offices 3-4, Germasogeia 4040']::TEXT[],
    'https://cypruspropertygallery.com/',
    ARRAY['+357 25 558800', '+357 25 731111', '+357 80 008384']::TEXT[],
    'info@cypruspropertygallery.com',
    'sales@cypruspropertygallery.com, newrequest@cypruspropertygallery.com',
    'Multi-primé (50+ prix) ; témoignages positifs sur le professionnalisme.',
    'Croissance stable avec large portefeuille.',
    8.0,
    'Focus fiable sur la classe moyenne.',
    55,
    22,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 20. Prime Property Group (incl. bbf)
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'Prime Property Group (incl. bbf)',
    2003,
    'Depuis 2003, développements holistiques dans plusieurs villes avec 150+ projets.',
    'Développements résidentiels et commerciaux premium.',
    'Appartements Prime ; 150+ au total.',
    'Limassol',
    ARRAY['Ambelakion 28 Street, Potamos Germasogeia, 4046 Limassol, Cyprus']::TEXT[],
    'https://bbf.com/en/',
    ARRAY['+357 25 558111']::TEXT[],
    'info@bbf.com',
    'sales@bbf.com',
    'Statut de pionnier avec retours positifs.',
    'Croissance rapide.',
    8.0,
    'Innovation bonne, mais plus récente que les vétérans.',
    150,
    22,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();

-- 21. Quality Group
INSERT INTO developers (
    name, founded_year, history, main_activities, key_projects, main_city,
    addresses, website, phone_numbers, email_primary, email_sales,
    reputation_reviews, financial_stability, rating_score, rating_justification,
    total_projects, years_experience, commission_rate, status
) VALUES (
    'Quality Group',
    1991,
    'Depuis 1991, portefeuille diversifié avec 225+ projets.',
    'Développement résidentiel et commercial ; basé à Larnaca avec des projets à Paphos.',
    'Blue Sky Villas ; Financial Centre ; 225+ projets.',
    'Paphos',
    ARRAY['41 Constantinou Paleologou Avenue, Larnaca 6036', '16 Inomenon Ethnon Str., 6042 Larnaca']::TEXT[],
    'https://qualitygroupcyprus.com/',
    ARRAY['+357 24 821855', '+357 80 007766']::TEXT[],
    'info@qualitygroupcyprus.com',
    'sales@qualitygroupcyprus.com',
    'Leader avec des notes de 4,4/5.',
    'Forte, bien établie.',
    8.0,
    'Polyvalence forte ; bon pour des besoins variés.',
    225,
    34,
    3.00,
    'active'
) ON CONFLICT (name) DO UPDATE SET
    founded_year = EXCLUDED.founded_year,
    history = EXCLUDED.history,
    main_activities = EXCLUDED.main_activities,
    key_projects = EXCLUDED.key_projects,
    main_city = EXCLUDED.main_city,
    addresses = EXCLUDED.addresses,
    website = EXCLUDED.website,
    phone_numbers = EXCLUDED.phone_numbers,
    email_primary = EXCLUDED.email_primary,
    email_sales = EXCLUDED.email_sales,
    reputation_reviews = EXCLUDED.reputation_reviews,
    financial_stability = EXCLUDED.financial_stability,
    rating_score = EXCLUDED.rating_score,
    rating_justification = EXCLUDED.rating_justification,
    total_projects = EXCLUDED.total_projects,
    years_experience = EXCLUDED.years_experience,
    updated_at = NOW();