-- Supprimer tous les projets existants et leurs dépendances
DELETE FROM project_amenities;
DELETE FROM project_nearby_amenities;
DELETE FROM project_images;
DELETE FROM project_documents;
DELETE FROM project_ai_imports;
DELETE FROM favorites;
DELETE FROM commissions WHERE project_id IN (SELECT id FROM projects);
DELETE FROM projects;

-- Insérer 3 nouveaux projets complets

-- Projet 1: Crona Groupe - Résidence Marina Bay
INSERT INTO projects (
  id,
  title,
  subtitle,
  description,
  detailed_description,
  price,
  price_from_new,
  price_to,
  price_per_m2,
  city,
  region,
  full_address,
  gps_latitude,
  gps_longitude,
  location,
  developer_id,
  status,
  project_status,
  construction_phase,
  completion_date_new,
  launch_date,
  construction_start,
  bedrooms_range,
  bathrooms_range,
  built_area_m2,
  land_area_m2,
  total_units_new,
  units_available_new,
  units_sold,
  floors_total,
  parking_spaces,
  storage_spaces,
  property_types,
  property_sub_type,
  features,
  amenities,
  golden_visa_eligible_new,
  vat_included,
  vat_rate_new,
  financing_available,
  financing_options,
  payment_plan,
  photos,
  floor_plan_urls,
  virtual_tour_url_new,
  video_url,
  meta_title_new,
  meta_description_new,
  meta_keywords,
  url_slug,
  featured_new,
  search_ranking_weight,
  ai_chatbot_enabled,
  energy_rating,
  design_style,
  finishing_level,
  furniture_status,
  smart_home_features,
  sustainability_certifications,
  compliance_certifications,
  permits_obtained,
  title_deed_status,
  legal_status,
  reservation_status,
  marketing_highlights,
  unique_selling_points,
  target_audience,
  neighborhood_description,
  proximity_sea_km,
  proximity_airport_km,
  proximity_city_center_km,
  proximity_highway_km,
  rental_yield_percent,
  roi_estimate_percent,
  cyprus_zone,
  translations,
  categorized_photos,
  units,
  interests
) VALUES (
  gen_random_uuid(),
  'Marina Bay Residences',
  'Luxueux appartements en bord de mer',
  'Découvrez Marina Bay Residences, un projet résidentiel de prestige offrant des appartements luxueux avec vue panoramique sur la mer Méditerranée.',
  'Marina Bay Residences redéfinit le luxe en bord de mer avec ses appartements contemporains dotés de finitions haut de gamme. Chaque résidence bénéficie de vues imprenables sur la mer, de terrasses spacieuses et d''un accès privilégié à la plage privée. Le projet comprend des espaces de vie généreux, des cuisines équipées avec des appareils premium, et des salles de bains spa. La résidence offre également un concierge 24h/24, une piscine infinity, un spa, une salle de sport et un parking souterrain sécurisé.',
  450000,
  350000,
  650000,
  4200,
  'Limassol',
  'Limassol District',
  '123 Marina Boulevard, Limassol, Chypre',
  34.6751,
  33.0431,
  '{"address": "123 Marina Boulevard", "city": "Limassol", "country": "Cyprus", "coordinates": {"lat": 34.6751, "lng": 33.0431}}',
  (SELECT id FROM developers WHERE name = 'Crona Group' LIMIT 1),
  'under_construction',
  'construction',
  'foundation',
  '2025-12-31',
  '2024-01-15',
  '2024-03-01',
  '1-4',
  '1-3',
  120.5,
  15000,
  48,
  42,
  6,
  8,
  10,
  5,
  ARRAY['apartment', 'penthouse'],
  ARRAY['luxury', 'modern', 'seafront'],
  ARRAY['sea_view', 'private_beach', 'modern_design', 'high_ceilings', 'marble_floors', 'smart_home', 'concierge', 'security_24h'],
  ARRAY['swimming_pool', 'spa', 'gym', 'concierge', 'private_beach', 'parking', 'storage', 'security'],
  true,
  true,
  5.00,
  true,
  '{"bank_financing": true, "developer_financing": true, "payment_plans": ["30_70", "50_50"]}',
  '{"deposit": 30, "phases": [{"percentage": 30, "stage": "signing"}, {"percentage": 40, "stage": "construction"}, {"percentage": 30, "stage": "completion"}]}',
  ARRAY['https://example.com/marina1.jpg', 'https://example.com/marina2.jpg', 'https://example.com/marina3.jpg'],
  ARRAY['https://example.com/floor1.pdf', 'https://example.com/floor2.pdf'],
  'https://example.com/virtual-tour-marina',
  'https://youtube.com/watch?v=marina-video',
  'Marina Bay Residences - Appartements de luxe Limassol | Crona Group',
  'Découvrez Marina Bay Residences à Limassol. Appartements de luxe avec vue mer, plage privée et services premium. Prix à partir de 350 000€.',
  ARRAY['appartements luxe Limassol', 'vue mer Chypre', 'Crona Group', 'golden visa', 'investissement immobilier'],
  'marina-bay-residences-limassol',
  true,
  9,
  true,
  'A+',
  'contemporary',
  'luxury',
  'furnished',
  '{"smart_lighting": true, "climate_control": true, "security_system": true, "automated_blinds": true}',
  ARRAY['LEED Gold', 'BREEAM Excellent'],
  ARRAY['ISO 9001', 'ISO 14001'],
  ARRAY['building_permit', 'environmental_permit', 'coastal_permit'],
  'ready',
  'approved',
  'available',
  ARRAY['vue mer panoramique', 'plage privée', 'finitions luxueuses', 'localisation premium'],
  ARRAY['architecture contemporaine', 'technologie smart home', 'services de concierge', 'accès plage direct'],
  ARRAY['investisseurs luxury', 'résidents permanents', 'golden visa applicants'],
  'Quartier premium de Limassol avec accès direct à la mer, proche des restaurants gastronomiques et centres commerciaux de luxe.',
  0.05,
  45,
  5,
  2,
  6.5,
  8.2,
  'limassol',
  '{"el": {"title": "Marina Bay Κατοικίες", "description": "Πολυτελή διαμερίσματα με θέα στη θάλασσα"}, "ru": {"title": "Резиденции Марина Бэй", "description": "Роскошные апартаменты с видом на море"}}',
  '[{"category": "exterior", "images": ["marina1.jpg", "marina2.jpg"]}, {"category": "interior", "images": ["marina3.jpg", "marina4.jpg"]}, {"category": "amenities", "images": ["marina5.jpg"]}]',
  ARRAY['{"bedrooms": 1, "bathrooms": 1, "area": 65, "price": 350000, "floor": "2-8", "available": 12}', '{"bedrooms": 2, "bathrooms": 2, "area": 95, "price": 450000, "floor": "2-8", "available": 18}', '{"bedrooms": 3, "bathrooms": 2, "area": 120, "price": 550000, "floor": "2-8", "available": 10}', '{"bedrooms": 4, "bathrooms": 3, "area": 180, "price": 650000, "floor": "7-8", "available": 2}']::jsonb[],
  ARRAY['{"icon": "🏖️", "title": "Plage privée", "description": "Accès exclusif à une plage privée"}', '{"icon": "🏊", "title": "Piscine infinity", "description": "Piscine à débordement avec vue mer"}', '{"icon": "🧘", "title": "Spa & Wellness", "description": "Centre spa complet avec hammam"}']::jsonb[]
),

-- Projet 2: LemonMaria Developers - Skyline Tower
(
  gen_random_uuid(),
  'Skyline Tower',
  'Tour résidentielle moderne au cœur de Nicosie',
  'Skyline Tower représente l''innovation architecturale à Nicosie avec ses appartements modernes et ses vues panoramiques sur la capitale.',
  'Skyline Tower s''élève majestueusement au centre de Nicosie, offrant 25 étages d''appartements modernes avec des vues spectaculaires sur la ville et les montagnes. Ce projet avant-gardiste propose des logements du studio au penthouse, tous équipés des dernières technologies. Les résidents bénéficient d''une piscine sur le toit, d''un centre de fitness ultramoderne, d''espaces de coworking, et d''un parking automatisé. La tour intègre des solutions écologiques innovantes et des espaces verts verticaux.',
  320000,
  180000,
  850000,
  3800,
  'Nicosia',
  'Nicosia District',
  '456 Central Avenue, Nicosia, Cyprus',
  35.1856,
  33.3823,
  '{"address": "456 Central Avenue", "city": "Nicosia", "country": "Cyprus", "coordinates": {"lat": 35.1856, "lng": 33.3823}}',
  (SELECT id FROM developers WHERE name = 'LemonMaria Developers' LIMIT 1),
  'under_construction',
  'construction',
  'structure',
  '2026-06-30',
  '2024-02-01',
  '2024-04-15',
  '0-4',
  '1-4',
  85.0,
  2500,
  120,
  95,
  25,
  25,
  2,
  10,
  ARRAY['studio', 'apartment', 'penthouse'],
  ARRAY['modern', 'urban', 'high_rise'],
  ARRAY['city_view', 'mountain_view', 'modern_design', 'high_tech', 'rooftop_pool', 'automated_parking', 'green_building', 'smart_home'],
  ARRAY['rooftop_pool', 'fitness_center', 'coworking', 'automated_parking', 'green_spaces', 'security', '24h_concierge'],
  true,
  true,
  5.00,
  true,
  '{"bank_financing": true, "developer_financing": true, "government_schemes": true}',
  '{"deposit": 25, "phases": [{"percentage": 25, "stage": "signing"}, {"percentage": 50, "stage": "construction"}, {"percentage": 25, "stage": "completion"}]}',
  ARRAY['https://example.com/skyline1.jpg', 'https://example.com/skyline2.jpg', 'https://example.com/skyline3.jpg'],
  ARRAY['https://example.com/skyline-floor1.pdf', 'https://example.com/skyline-floor2.pdf'],
  'https://example.com/virtual-tour-skyline',
  'https://youtube.com/watch?v=skyline-video',
  'Skyline Tower Nicosia - Appartements modernes | LemonMaria Developers',
  'Skyline Tower à Nicosia. Tour résidentielle moderne de 25 étages avec vue panoramique. Appartements du studio au penthouse.',
  ARRAY['appartements Nicosia', 'tour résidentielle', 'LemonMaria', 'investissement Chypre', 'vue panoramique'],
  'skyline-tower-nicosia',
  true,
  8,
  true,
  'A',
  'modern',
  'premium',
  'semi_furnished',
  '{"smart_home_system": true, "voice_control": true, "energy_management": true, "automated_security": true}',
  ARRAY['BREEAM Very Good', 'Green Building Council'],
  ARRAY['ISO 50001', 'OHSAS 18001'],
  ARRAY['high_rise_permit', 'urban_planning_permit', 'environmental_assessment'],
  'in_progress',
  'approved',
  'pre_launch',
  ARRAY['tour de 25 étages', 'vues panoramiques', 'technologies avancées', 'localisation centrale'],
  ARRAY['design architectural unique', 'parking automatisé', 'espaces verts verticaux', 'centre fitness premium'],
  ARRAY['jeunes professionnels', 'investisseurs urbains', 'familles modernes'],
  'Centre-ville de Nicosie, proche des ministères, banques centrales, universités et centres commerciaux majeurs.',
  null,
  15,
  1,
  3,
  7.8,
  9.1,
  'nicosia',
  '{"el": {"title": "Πύργος Skyline", "description": "Μοντέρνος κατοικημένος πύργος στη Λευκωσία"}, "ru": {"title": "Башня Скайлайн", "description": "Современная жилая башня в Никосии"}}',
  '[{"category": "exterior", "images": ["skyline1.jpg", "skyline2.jpg"]}, {"category": "interior", "images": ["skyline3.jpg", "skyline4.jpg"]}, {"category": "views", "images": ["skyline5.jpg", "skyline6.jpg"]}]',
  ARRAY['{"bedrooms": 0, "bathrooms": 1, "area": 35, "price": 180000, "floor": "3-20", "available": 25}', '{"bedrooms": 1, "bathrooms": 1, "area": 55, "price": 250000, "floor": "3-20", "available": 35}', '{"bedrooms": 2, "bathrooms": 2, "area": 75, "price": 320000, "floor": "3-20", "available": 30}', '{"bedrooms": 3, "bathrooms": 2, "area": 110, "price": 480000, "floor": "15-20", "available": 5}', '{"bedrooms": 4, "bathrooms": 4, "area": 200, "price": 850000, "floor": "21-25", "available": 0}']::jsonb[],
  ARRAY['{"icon": "🏙️", "title": "Vue panoramique", "description": "Vues à 360° sur Nicosie et les montagnes"}', '{"icon": "🤖", "title": "Parking automatisé", "description": "Système de parking robotisé intelligent"}', '{"icon": "🌱", "title": "Jardins verticaux", "description": "Espaces verts intégrés sur toute la hauteur"}']::jsonb[]
),

-- Projet 3: Mountain View Villas
(
  gen_random_uuid(),
  'Mountain View Villas',
  'Villas de luxe avec vue sur les montagnes de Troodos',
  'Mountain View Villas offre des villas exclusives dans un cadre naturel exceptionnel, alliant luxe moderne et authenticité chypriote.',
  'Nichées dans les collines pittoresques surplombant Limassol, les Mountain View Villas proposent un art de vivre unique en harmonie avec la nature. Ces 12 villas exclusives, construites avec des matériaux locaux nobles, offrent des espaces de vie généreux, des piscines privées et des jardins méditerranéens. Chaque villa bénéficie d''une vue imprenable sur les montagnes de Troodos et la mer au loin. Le projet privilégie l''architecture bioclimatique, l''énergie solaire et la récupération d''eau de pluie.',
  950000,
  750000,
  1500000,
  5200,
  'Limassol Hills',
  'Limassol District',
  '789 Mountain Road, Limassol Hills, Cyprus',
  34.7041,
  32.9984,
  '{"address": "789 Mountain Road", "city": "Limassol Hills", "country": "Cyprus", "coordinates": {"lat": 34.7041, "lng": 32.9984}}',
  null,
  'pre_launch',
  'planning',
  'design',
  '2027-03-31',
  '2024-06-01',
  '2024-09-01',
  '3-5',
  '3-5',
  280.0,
  1200,
  12,
  8,
  4,
  12,
  8,
  24,
  ARRAY['villa', 'luxury_villa'],
  ARRAY['luxury', 'mountain', 'exclusive', 'eco_friendly'],
  ARRAY['mountain_view', 'sea_view', 'private_pool', 'garden', 'eco_design', 'solar_energy', 'stone_construction', 'luxury_finishes'],
  ARRAY['private_pool', 'garden', 'bbq_area', 'garage', 'storage', 'solar_panels', 'rainwater_harvesting'],
  true,
  false,
  0.00,
  true,
  '{"bank_financing": true, "developer_financing": true, "eco_incentives": true}',
  '{"deposit": 35, "phases": [{"percentage": 35, "stage": "signing"}, {"percentage": 35, "stage": "foundation"}, {"percentage": 30, "stage": "completion"}]}',
  ARRAY['https://example.com/mountain1.jpg', 'https://example.com/mountain2.jpg', 'https://example.com/mountain3.jpg'],
  ARRAY['https://example.com/mountain-plans.pdf'],
  'https://example.com/virtual-tour-mountain',
  'https://youtube.com/watch?v=mountain-video',
  'Mountain View Villas - Villas de luxe Limassol Hills | Immobilier Premium',
  'Mountain View Villas dans les collines de Limassol. 12 villas exclusives avec vue montagne et mer. Architecture écologique et matériaux nobles.',
  ARRAY['villas luxe Chypre', 'vue montagne Troodos', 'Limassol Hills', 'villa écologique', 'investissement premium'],
  'mountain-view-villas-limassol',
  true,
  10,
  false,
  'A++',
  'mediterranean',
  'luxury',
  'unfurnished',
  '{"solar_management": true, "rainwater_system": true, "smart_irrigation": true, "eco_monitoring": true}',
  ARRAY['Passive House', 'Nearly Zero Energy Building'],
  ARRAY['Cradle to Cradle', 'FSC Certified Materials'],
  ARRAY['villa_permit', 'mountain_development_permit', 'eco_certification'],
  'pending',
  'under_review',
  'exclusive_preview',
  ARRAY['villas exclusives', 'cadre naturel exceptionnel', 'architecture bioclimatique', 'matériaux nobles locaux'],
  ARRAY['vue double montagne-mer', 'construction écologique', 'piscines privées chauffées', 'jardins méditerranéens'],
  ARRAY['ultra_high_net_worth', 'nature_lovers', 'eco_conscious_buyers'],
  'Collines paisibles de Limassol offrant intimité totale, air pur et proximité de la nature, à 15 minutes du centre-ville.',
  25,
  null,
  15,
  8,
  5.8,
  7.5,
  'limassol',
  '{"el": {"title": "Βίλες Mountain View", "description": "Πολυτελείς βίλες με θέα στα βουνά"}, "ru": {"title": "Виллы Маунтин Вью", "description": "Роскошные виллы с видом на горы"}}',
  '[{"category": "exterior", "images": ["mountain1.jpg", "mountain2.jpg"]}, {"category": "views", "images": ["mountain3.jpg", "mountain4.jpg"]}, {"category": "gardens", "images": ["mountain5.jpg"]}]',
  ARRAY['{"bedrooms": 3, "bathrooms": 3, "area": 220, "price": 750000, "plot_size": 800, "available": 3}', '{"bedrooms": 4, "bathrooms": 4, "area": 280, "price": 950000, "plot_size": 1000, "available": 3}', '{"bedrooms": 5, "bathrooms": 5, "area": 350, "price": 1500000, "plot_size": 1500, "available": 2}']::jsonb[],
  ARRAY['{"icon": "🏔️", "title": "Vue double", "description": "Vue panoramique montagnes et mer"}', '{"icon": "🌱", "title": "Éco-construction", "description": "Matériaux locaux et énergies renouvelables"}', '{"icon": "🏊", "title": "Piscine chauffée", "description": "Piscine privée chauffée à l''énergie solaire"}']::jsonb[]
);