-- Insérer une propriété penthouse complète avec tous les équipements
-- Récupérer d'abord un projet et un bâtiment existants
WITH project_data AS (
  SELECT id as project_id FROM projects_clean LIMIT 1
),
building_data AS (
  SELECT id as building_id FROM buildings_enhanced LIMIT 1
)
INSERT INTO properties_final (
  unit_code,
  property_type,
  floor_number,
  project_id,
  building_id,
  bedrooms,
  bathrooms,
  wc_separate,
  internal_area_m2,
  price,
  covered_veranda_m2,
  uncovered_veranda_m2,
  garden_area_m2,
  storage_area_m2,
  has_parking_space,
  parking_spaces_count,
  property_features,
  has_balcony,
  has_terrace,
  has_garden,
  has_private_pool,
  has_jacuzzi,
  has_fireplace,
  has_storage_room,
  has_maid_room,
  kitchen_type,
  furniture_status,
  status,
  title_deed_status,
  title_deed_number,
  orientation,
  view_type,
  vat_rate,
  reservation_fee,
  down_payment_percent,
  financing_available,
  discount_percentage
)
SELECT 
  'PH-DELUXE-001',
  'penthouse',
  25,
  p.project_id,
  b.building_id,
  6,
  5,
  true,
  900.0,
  1500000.0,
  150.0,
  300.0,
  500.0,
  50.0,
  true,
  4,
  ARRAY['Réfrigérateur', 'Congélateur', 'Lave-vaisselle', 'Four', 'Micro-ondes', 'Plaque de cuisson', 'Hotte aspirante', 'Machine à café', 'Cave à vin', 'Système de sécurité', 'Caméras surveillance', 'Contrôle éclairage', 'Thermostat intelligent', 'Interphone vidéo', 'Domotique centralisée', 'Alarme incendie', 'Détecteurs fumée', 'Caméras 360°', 'Détecteurs mouvement', 'Alarme périmétrique', 'Contrôle accès biométrique', 'Surveillance 24h/24', 'Safe room', 'Détecteurs bris de glace', 'Système anti-intrusion'],
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  'luxury',
  'fully_furnished',
  'available',
  'available',
  'TD-2024-PH-001',
  'south',
  'panoramic',
  5.0,
  10000.0,
  30.0,
  true,
  6.25
FROM project_data p, building_data b;